// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://mtxeqjxzmplrleryydxe.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10eGVxanh6bXBscmxlcnl5ZHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIwNTEzNjQsImV4cCI6MjA0NzYyNzM2NH0.zRfF68T3ySYuQkrJkpjgtCmlgUqAkznLzvmFQyS55B8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);